services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    IndyDevGuy\AssetInjectorBundle\Service\AssetInjector:
        arguments: ['@event_dispatcher']

    IndyDevGuy\AssetInjectorBundle\DataCollector\AssetInjectorCollector:
        arguments: ['@IndyDevGuy\AssetInjectorBundle\Service\AssetInjector']
        tags:
            -
                name: data_collector
                template: '@AssetInjector/data_collector/assetinjector.html.twig'
                id: 'asset_injector.assetinjector_collector'